# Generated by Django 5.1.4 on 2025-01-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="csvdata",
            name="uploaded_at",
        ),
        migrations.AddField(
            model_name="csvdata",
            name="csv_file",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
        migrations.AlterField(
            model_name="csvdata",
            name="data",
            field=models.TextField(),
        ),
    ]
